name: flutter_sml
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_swiper : ^1.1.6
  flutter_svg : ^0.14.0
  flutter_screenutil: ^0.5.3
  path_drawing: ^0.4.1
  video_player: ^0.8.0
  chewie: ^0.9.6
  provider: ^3.1.0
  city_pickers: ^0.1.23
  image_picker: ^0.6.1+4
  dio: ^2.1.16
  dependencies:
  flutter_easyrefresh: ^2.0.4
  pull_to_refresh: ^1.5.5
  flutter_spinkit: ^4.0.0
  transparent_image: ^1.0.0
  fluttertoast: ^3.1.3
  flutter_localizations:
    sdk: flutter
  flutter_custom_calendar:
    git:
      url: https://github.com/LXD312569496/flutter_custom_calendar.git
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.6.7

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/shenmujidi.svg
   - images/shenmujidi.png
   - images/2.0x/shenmujidi.png
   - images/3.0x/shenmujidi.png
   - images/shenmukaquan.png
   - images/2.0x/shenmukaquan.png
   - images/3.0x/shenmukaquan.png
   - images/shenmuchuxing.png
   - images/2.0x/shenmuchuxing.png
   - images/3.0x/shenmuchuxing.png
   - images/shenmucanyin.png
   - images/2.0x/shenmucanyin.png
   - images/3.0x/shenmucanyin.png
   - images/shenmuzhusu.png
   - images/2.0x/shenmuzhusu.png
   - images/3.0x/shenmuzhusu.png
   - images/shenmugouwu.png
   - images/2.0x/shenmugouwu.png
   - images/3.0x/shenmugouwu.png
   - images/shenmuyule.png
   - images/2.0x/shenmuyule.png
   - images/3.0x/shenmuyule.png
   - images/zhoubianyou.png
   - images/2.0x/zhoubianyou.png
   - images/3.0x/zhoubianyou.png
   - images/tongzhi.png
   - images/2.0x/tongzhi.png
   - images/3.0x/tongzhi.png
   - images/xiaoxi.png
   - images/2.0x/xiaoxi.png
   - images/3.0x/xiaoxi.png
   - images/gonggao.png
   - images/2.0x/gonggao.png
   - images/3.0x/gonggao.png
   - images/wodeqianbao.png
   - images/2.0x/wodeqianbao.png
   - images/3.0x/wodeqianbao.png
   - images/wodedongtai.png
   - images/2.0x/wodedongtai.png
   - images/3.0x/wodedongtai.png
   - images/wodeshenmu.png
   - images/2.0x/wodeshenmu.png
   - images/3.0x/wodeshenmu.png
   - images/zhuangtailan.png
   - images/2.0x/zhuangtailan.png
   - images/3.0x/zhuangtailan.png
   - images/3.0x/zhuangtailan.png
   - images/jia-v.png
   - images/2.0x/jia-v.png
   - images/3.0x/jia-v.png
   - images/loginbg.png
   - images/2.0x/loginbg.png
   - images/3.0x/loginbg.png
   - images/logo.png
   - images/2.0x/logo.png
   - images/3.0x/logo.png
   - images/register.png
   - images/2.0x/register.png
   - images/3.0x/register.png
   - images/border.png
   - images/2.0x/border.png
   - images/3.0x/border.png
   - images/itransfer.png
   - images/2.0x/itransfer.png
   - images/3.0x/itransfer.png
   - images/message.png
   - images/2.0x/message.png
   - images/3.0x/message.png
   - images/money.png
   - images/2.0x/money.png
   - images/3.0x/money.png
   - images/weixin.png
   - images/2.0x/weixin.png
   - images/3.0x/weixin.png
   - images/mybg.png
   - images/2.0x/mybg.png
   - images/3.0x/mybg.png
   - images/dongtai.png
   - images/2.0x/dongtai.png
   - images/3.0x/dongtai.png
   - images/hui.png
   - images/2.0x/hui.png
   - images/3.0x/hui.png
   - videos/video.mp4
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: iconfont
      fonts:
        - asset: fonts/iconfont.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
